# Generated by Django 5.2.6 on 2025-09-07 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Ritesh Chandra', max_length=100)),
                ('headline', models.CharField(default='Full-stack developer — Django, Python, responsive UI, and clean UX.', max_length=200)),
                ('hero_greeting', models.CharField(default="Hi, I'm", max_length=60)),
                ('accent_name', models.CharField(default='Ritesh', max_length=50)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('about_text_1', models.TextField(blank=True)),
                ('about_text_2', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='Bootstrap icon class, e.g. "bi bi-github"', max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='home.profile')),
            ],
        ),
    ]
