# Generated by Django 5.2.6 on 2025-09-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='color_class',
            field=models.CharField(default='bg-success', max_length=50),
        ),
    ]
